import type { Metadata } from "next";
import { notFound } from "next/navigation";
import ArtifactGallery from "@/components/ArtifactGallery";
import { data, modelOrder, resultsForModel, scenarioOrder, type ModelKey } from "@/lib/catalog";
import styles from "../../library.module.css";

type Props = { params: Promise<{ slug: string }> };

export function generateStaticParams() {
  return modelOrder.map((slug) => ({ slug }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const model = data.models[slug as ModelKey];
  if (!model) return {};
  const title = `${model.name} library`;
  const description = `All ${scenarioOrder.length} BenchViz one-shot HTML animations generated by ${model.name} (${model.vendor}).`;
  return {
    title,
    description,
    alternates: { canonical: `/models/${slug}` },
    openGraph: { title, description, url: `/models/${slug}` },
  };
}

export default async function ModelPage({ params }: Props) {
  const { slug } = await params;
  const model = data.models[slug as ModelKey];
  if (!model) notFound();
  const results = resultsForModel(slug as ModelKey);

  return (
    <main className={styles.page}>
      <p className={styles.kicker}>{model.vendor}</p>
      <h1>{model.name}</h1>
      <p className={styles.lead}>
        Library view for {model.name}: one published artifact per challenge, generated one-shot
        with no human edits.
      </p>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "CollectionPage",
            name: `${model.name} · BenchViz library`,
            description: `All BenchViz one-shot HTML animations generated by ${model.name}.`,
          }),
        }}
      />
      <ArtifactGallery
        results={results}
        hrefFor={(result) => ({
          label: data.scenarios[result.scenario as keyof typeof data.scenarios].name,
          href: `/challenges/${result.scenario}`,
        })}
      />
    </main>
  );
}
